<?php

namespace SUWE\SondageBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAvailableLots()
    {
        return $this->createQueryBuilder('l')
            ->where('l.isAvailable = :available')
            ->setParameter('available', true)
            ->getQuery()
            ->getResult();
    }
}