<?php

namespace SUWE\SondageBundle\Repository;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findSondage($sondageId)
    {
        return $this->createQueryBuilder('s')
            ->where('s.id = :id')
            ->setParameter('id', $sondageId)
            ->leftJoin('s.questions', 'q')
            ->addSelect('q')
            ->leftJoin('q.responses', 'r')
            ->addSelect('r')
            ->getQuery()
            ->getResult();
    }
}
