suwe_consumer:
    resource: "@SUWECoreBundle/Controller/ConsumerController.php"
    type:     annotation
    prefix:   /

suwe_announceur:
    resource: "@SUWECoreBundle/Controller/AnnonceurController.php"
    type: annotation
    prefix: /annonceur

#API

suwe_user_api:
    prefix: api/user
    resource: "@SUWEUserBundle/Controller/UserApiController.php"
    type: rest

#FOSUser routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /mon-compte

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset-mot-de-passe

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /mon-compte

fos_user_registration_confirmed:
    path: /registration/confirmed
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dashboard