# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

#Redirection when user is logged-in

    suwe_user.listener.registration_confirmed:
         class: SUWE\UserBundle\EventListener\RegistrationListener
         arguments: ['@assets.packages','@router']
         tags:
           - { name: kernel.event_subscriber}